[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "util-bot-with-cogs"
version = "0.1.0"
[tool.poetry.dependencies]
discord = "^1.0"
flask = "^1.1"
jishaku = "^1.17"
pandas = "^0.25.3"
pyperclip = "^1.7"
python = "^3.8"
python-dotenv = "^0.10.3"
[tool.poetry.dev-dependencies]
